Import('env')

headers = []
instances = []
sources = []
aliases = {}

periph = env['PLATFORM_SPEC'].get('periph', {})

if 'stm32_i2c' in periph:
    headers.append('stm32_i2c.h')
    for name, data in periph['stm32_i2c'].items():
        instances.append({
            'type': 'STM32_I2C_t<STM32_I2C_reg_%s_t>' % data['type'],
            'name': name,
            'args': [data['offset']],
        })

env.Jinja2('i2c.h', '../templates/periph_instances.h.j2', headers = headers, instances = instances, aliases = aliases)

Return('sources')
