Import('env')

headers = []
instances = []
sources = []
aliases = {}

periph = env['PLATFORM_SPEC'].get('periph', {})

if 'stm32_pwr' in periph:
    headers.append('stm32_pwr.h')
    for name, data in periph['stm32_pwr'].items():
        instances.append({
            'type': 'STM32_PWR_t<STM32_PWR_reg_%s_t>' % data['type'],
            'name': name,
            'args': [data['offset']],
        })

env.Jinja2('pwr.h', '../templates/periph_instances.h.j2', headers = headers, instances = instances, aliases = aliases)

Return('sources')

